AY2223S2-CS2103-F10-1/tp

README.md, docs/_config.yml, docs/index.md
=> Update readme and page document

docs/AboutUs.md
=> Updated about us to fulfill v1.1

docs/UserGuide.md
=> UG - modified help writeup to match current OfficeConnect

src/test/java/seedu/address/model/OfficeConnectModelTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java
#26 
Adds test case for adding/deleting:
- task
- personTask
=> Add OfficeConnectModelTest

src/main/java/seedu/address/storage/JsonAdaptedPersonTask.java, src/main/java/seedu/address/storage/JsonSerializablePersonTaskBook.java, src/main/java/seedu/address/storage/StorageManager.java, src/test/java/seedu/address/storage/StorageManagerTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java
#26 
This PR fix the bug that unable to read personTask from local storage.
=> Add integration test and fix bug for task and personTask storage

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java
Fix bugs in addtask that caused parser to parse incorrectly
Update UG on updated format of addtask
=> Fix bugs in addtask that caused parser to parse incorrectly

src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/DeleteTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTaskCommandParser.java, src/main/java/seedu/address/model/RepositoryModelManager.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/commands/ListTaskCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Add necessary JUnit tests for DeleteTask, DeleteTaskCommandParser
Resolve #6
=> Create DeleteTask command, DeleteTaskCommandParser 

README.md, docs/DeveloperGuide.md, docs/UserGuide.md, docs/team/nicklelodeon.md
=> Update documentations for addtask command

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonListPanel.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/java/seedu/address/ui/TaskListPanel.java, src/main/resources/view/MainWindow.fxml, src/main/resources/view/TaskListCard.fxml, src/main/resources/view/TaskListPanel.fxml
Resolve #63 
A quick implementation of showing task from GUI.
Hope can help you in implementing your features.
Feel free to overwrite the code and design in this pr.
=> Main page gui show detail

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/MarkCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkCommandParser.java, src/main/java/seedu/address/model/Relationship.java, src/main/java/seedu/address/model/UniqueItemList.java, src/main/java/seedu/address/model/mapping/PersonTask.java, src/main/java/seedu/address/model/task/Status.java, src/main/java/seedu/address/model/task/Task.java, src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java, src/test/java/seedu/address/logic/commands/MarkCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/MarkCommandParserTest.java, src/test/java/seedu/address/model/ItemStub.java, src/test/java/seedu/address/model/mapping/PersonTaskTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TypicalTasks.java
=> Create mark command and JUnit tests for the commands

src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/UnmarkCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java, src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/UnmarkCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java, src/test/java/seedu/address/testutil/TypicalTasks.java
=> Add Unmark Command and JUnit tests

docs/UserGuide.md, src/main/java/seedu/address/commons/core/Messages.java, src/main/java/seedu/address/logic/commands/ListAllCommand.java, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/main/java/seedu/address/logic/commands/ReviewCommand.java, src/main/java/seedu/address/logic/commands/ReviewTaskCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ReviewCommandParser.java, src/main/java/seedu/address/logic/parser/ReviewTaskCommandParser.java, src/main/java/seedu/address/model/Repository.java, src/main/java/seedu/address/model/RepositoryModelManager.java, src/main/java/seedu/address/model/mapping/PersonTask.java, src/main/java/seedu/address/model/person/NameContainsExactKeywordsPredicate.java, src/main/java/seedu/address/model/task/SubjectContainsExactKeywordsPredicate.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ListAllCommandTest.java, src/test/java/seedu/address/logic/commands/ReviewCommandTest.java, src/test/java/seedu/address/logic/commands/ReviewTaskCommandTest.java, src/test/java/seedu/address/logic/parser/ReviewCommandParserTest.java, src/test/java/seedu/address/logic/parser/ReviewTaskCommandParserTest.java
=> Implement Review, Reviewtask and Listall features

docs/DeveloperGuide.md, docs/team/cyiting.md, docs/team/guo-kecheng.md, docs/team/kayyenl.md, docs/team/nicklelodeon.md, docs/team/spwwj.md, src/main/java/seedu/address/logic/commands/ListTaskCommand.java, src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
Resolve #70 
Add repo-sense link for all members
=> Add ListTask Command documentation

docs/UserGuide.md, src/main/java/seedu/address/ui/HelpWindow.java
Minor removal of initialize method in HelpWindow (found out it was a redundancy). Doesn't affect the overall code's performance
=> Remove redundant method and improved documentation

README.md, docs/DeveloperGuide.md, docs/UserGuide.md
=> Update ReadMe, User Guide and Developer Guide

docs/DeveloperGuide.md, docs/UserGuide.md, docs/team/nicklelodeon.md, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddTaskCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/testutil/TaskBuilder.java, src/test/java/seedu/address/testutil/TypicalTasks.java
Resolve #71 
Refactor subject to title
=> Add deletetask documentation, change subject to title

build.gradle
=> Enable assertion in build.gradle

docs/DeveloperGuide.md
Reformatted help window implementation.
=> V1.3 DG Help second update

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/logic/commands/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/logic/commands/MarkCommand.java, src/main/java/seedu/address/logic/commands/UnmarkCommand.java, src/main/java/seedu/address/logic/parser/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditTaskCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/shared/Datetime.java, src/main/java/seedu/address/model/task/Task.java, src/main/java/seedu/address/model/util/TaskBuilder.java, src/main/java/seedu/address/model/util/TypicalTasks.java, src/main/java/seedu/address/storage/JsonAdaptedTask.java, src/main/java/seedu/address/ui/CommandBox.java, src/main/java/seedu/address/ui/TaskCard.java, src/main/resources/css/TaskCardView.css, src/main/resources/view/TaskListCard.fxml, src/test/java/seedu/address/model/shared/DatetimeTest.java, src/test/java/seedu/address/model/task/TaskTest.java, src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Add datetime feature and fix some gui bugs
=> Add datetime

docs/DeveloperGuide.md, docs/team/cyiting.md
=> Update PPP and DG

src/main/java/seedu/address/logic/commands/AssignCommand.java, src/main/java/seedu/address/logic/commands/MarkCommand.java, src/main/java/seedu/address/logic/commands/UnmarkCommand.java, src/main/java/seedu/address/model/OfficeConnectModel.java
=> Update code to conform to Law of Demeter

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/EditTaskCommand.java, src/main/java/seedu/address/logic/commands/IndexCommand.java, src/main/java/seedu/address/logic/commands/MarkCommand.java, src/main/java/seedu/address/logic/commands/UnmarkCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/OfficeConnectModel.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTaskCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditTaskCommandTest.java, src/test/java/seedu/address/logic/commands/MarkCommandTest.java, src/test/java/seedu/address/logic/commands/UnmarkCommandTest.java
=> Fix Person and Task list state issue on tags label
